#define SCALE_SIZE_MONSTER 0.008f
#define SCALE_SIZE_ITEM 0.2f 
#define TILE_OFFSET 2.0f
#define MONSTER_HEIGHT_POS 0.7f
enum eObjectTypes
{
	UNKNOWN=0,ITEM_RED,ITEM_GREEN,ITEM_YELLOW,ITEM_BLUE,MONSTER,BARBARIAN
};